version: "3"

vars:
  goos: linux
  goarch: amd64
  plugin_out: build/plugins
  middleware_out: build/middlewares
  bin_dir: .bin

tasks:
  default:
    desc: Build binary and plugins
    deps:
      - build
      - plugins

  build:
    desc: Build main gateway binary
    cmds:
      - mkdir -p {{.bin_dir}}
      - CGO_ENABLED=1 go build -o {{.bin_dir}}/tokka ./cmd/gateway/main.go

  plugins:
    desc: Build plugins and middlewares
    cmds:
      - mkdir -p {{.plugin_out}}
      - mkdir -p {{.middleware_out}}
      - GOOS={{.goos}} GOARCH={{.goarch}} CGO_ENABLED=1 go build -buildmode=plugin -o {{.middleware_out}}/logger.so ./builtin/middlewares/logger/middleware.go
      - GOOS={{.goos}} GOARCH={{.goarch}} CGO_ENABLED=1 go build -buildmode=plugin -o {{.middleware_out}}/recoverer.so ./builtin/middlewares/recoverer/middleware.go
      - GOOS={{.goos}} GOARCH={{.goarch}} CGO_ENABLED=1 go build -buildmode=plugin -o {{.middleware_out}}/compressor.so ./builtin/middlewares/compressor/middleware.go
      - GOOS={{.goos}} GOARCH={{.goarch}} CGO_ENABLED=1 go build -buildmode=plugin -o {{.plugin_out}}/camelify.so ./builtin/plugins/camelify/plugin.go
      - GOOS={{.goos}} GOARCH={{.goarch}} CGO_ENABLED=1 go build -buildmode=plugin -o {{.plugin_out}}/snakeify.so ./builtin/plugins/snakeify/plugin.go

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build/middlewares build/plugins .bin

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  test:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
