// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mock/metrics.go -package=mock Metrics
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	metric "github.com/starwalkn/tokka/internal/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// DecRequestsInFlight mocks base method.
func (m *MockMetrics) DecRequestsInFlight() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecRequestsInFlight")
}

// DecRequestsInFlight indicates an expected call of DecRequestsInFlight.
func (mr *MockMetricsMockRecorder) DecRequestsInFlight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecRequestsInFlight", reflect.TypeOf((*MockMetrics)(nil).DecRequestsInFlight))
}

// IncFailedRequestsTotal mocks base method.
func (m *MockMetrics) IncFailedRequestsTotal(arg0 metric.FailReason) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFailedRequestsTotal", arg0)
}

// IncFailedRequestsTotal indicates an expected call of IncFailedRequestsTotal.
func (mr *MockMetricsMockRecorder) IncFailedRequestsTotal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFailedRequestsTotal", reflect.TypeOf((*MockMetrics)(nil).IncFailedRequestsTotal), arg0)
}

// IncRequestsInFlight mocks base method.
func (m *MockMetrics) IncRequestsInFlight() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRequestsInFlight")
}

// IncRequestsInFlight indicates an expected call of IncRequestsInFlight.
func (mr *MockMetricsMockRecorder) IncRequestsInFlight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRequestsInFlight", reflect.TypeOf((*MockMetrics)(nil).IncRequestsInFlight))
}

// IncRequestsTotal mocks base method.
func (m *MockMetrics) IncRequestsTotal() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRequestsTotal")
}

// IncRequestsTotal indicates an expected call of IncRequestsTotal.
func (mr *MockMetricsMockRecorder) IncRequestsTotal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRequestsTotal", reflect.TypeOf((*MockMetrics)(nil).IncRequestsTotal))
}

// IncResponsesTotal mocks base method.
func (m *MockMetrics) IncResponsesTotal(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncResponsesTotal", arg0)
}

// IncResponsesTotal indicates an expected call of IncResponsesTotal.
func (mr *MockMetricsMockRecorder) IncResponsesTotal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncResponsesTotal", reflect.TypeOf((*MockMetrics)(nil).IncResponsesTotal), arg0)
}

// UpdateRequestsDuration mocks base method.
func (m *MockMetrics) UpdateRequestsDuration(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateRequestsDuration", arg0)
}

// UpdateRequestsDuration indicates an expected call of UpdateRequestsDuration.
func (mr *MockMetricsMockRecorder) UpdateRequestsDuration(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRequestsDuration", reflect.TypeOf((*MockMetrics)(nil).UpdateRequestsDuration), arg0)
}
